version: "3.5"

networks:
  thvnet:
    name: thvnet

services:
  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: thv3_elasticsearch
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - thvnet

  cortex:
    image: thehiveproject/cortex:3.1
    container_name: thv3_cortex
    ports:
      - "0.0.0.0:9001:9001"
    depends_on:
      - elasticsearch
    networks:
      - thvnet
    volumes:
      - ./cortex/Cortex-Analyzers:/etc/Cortex-Analyzers
      - ./cortex/application.conf:/etc/cortex/application.conf

  thehive:
    image: thehiveproject/thehive:3.5
    container_name: thv3_thehive
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
    depends_on:
      - elasticsearch
      - cortex
    networks:
      - thvnet

  webhook_debug:
    build: ./webhook_debug
    container_name: thv3_webhook_debug
    ports:
      - "5000:5000"
    volumes:
      - ./webhook_debug:/code
    networks:
      - thvnet
